<?php
/**
 * Plugin Name:       Clone Post with Unsaved Changes to a Draft
 * Plugin URI:        https://wordpress.org/plugins/clone-post-unsaved-changes/
 * Description:       Adds a "Save As" button to the block editor that clones the current post or page into a new draft.
 * Version:           1.0.1
 * Requires at least: 6.6
 * Requires PHP:      7.4
 * Author:            Alimuzzaman Alim
 * Author URI:        https://profiles.wordpress.org/alimuzzamanalim/
 * License:           GPLv2 or later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       clone-post-unsaved-changes
 * Domain Path:       /languages
 *
 * @package ClonePostUnsavedChanges
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

add_action( 'enqueue_block_editor_assets', 'clone_post_unsaved_changes_enqueue_block_editor_assets' );

/**
 * Enqueue the compiled block-editor bundle and register its JS translations.
 *
 * Reads the dependency/version manifest generated by wp-scripts so the script
 * declares the exact @wordpress/* dependencies it was built against.
 *
 * @return void
 */
function clone_post_unsaved_changes_enqueue_block_editor_assets() {
	$asset_path = plugin_dir_path( __FILE__ ) . 'build/index.asset.php';

	// Bail quietly if the bundle hasn't been built yet (run `pnpm build`).
	if ( ! file_exists( $asset_path ) ) {
		return;
	}

	$asset = include $asset_path;

	wp_enqueue_script(
		'clone-post-unsaved-changes-script',
		plugins_url( 'build/index.js', __FILE__ ),
		$asset['dependencies'],
		$asset['version'],
		true
	);

	// Make the @wordpress/i18n strings (__/sprintf) in the bundle translatable.
	wp_set_script_translations(
		'clone-post-unsaved-changes-script',
		'clone-post-unsaved-changes',
		plugin_dir_path( __FILE__ ) . 'languages'
	);
}
